name: ci-wf

on:
  pull_request:
    branches:  
      - develop
    types:
      - opened
      - synchronize

  push:
    branches:
      - develop

jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome step
        run: echo "CI Pipeline for this repo"
      - name: Checkout repo
        uses: action/checkout@v4
      - name: lint HTML Files 
        run: npx htmlhint "**/*.html"
      - name: Lint CSS Files
        run: npx stylelint "**/*.css"  
